/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Card;
import java.awt.Font;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author tranh
 */
public class PickColorFrame extends javax.swing.JFrame {

    private Card.Color wildcolor = null;
    Boolean allow = false;
    PopUp popup;
    
    
    public PickColorFrame() {
        initComponents();
    }
    
    public PickColorFrame(PopUp pop){
        initComponents();
        popup = pop;
    }
    
    public Card.Color choseColor(Card card){
        if (card.getColor() == Card.Color.Wild){
            this.setVisible(true);
            this.setResizable(false);
            this.setBounds(750, 40 , 700, 800);
        }
        return card.getColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        redBtn = new javax.swing.JButton();
        blueBtn = new javax.swing.JButton();
        greenBtn = new javax.swing.JButton();
        yellowBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Choose Color");

        redBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        redBtn.setText("Red");
        redBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redBtnActionPerformed(evt);
            }
        });

        blueBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        blueBtn.setText("Blue");
        blueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueBtnActionPerformed(evt);
            }
        });

        greenBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        greenBtn.setText("Green");
        greenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenBtnActionPerformed(evt);
            }
        });

        yellowBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yellowBtn.setText("Yellow");
        yellowBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yellowBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(redBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(blueBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(greenBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(yellowBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addContainerGap(170, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(redBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(blueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(greenBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(yellowBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueBtnActionPerformed
        wildcolor = Card.Color.Blue;
        JLabel msg = new JLabel("The Wild Card Color is Blue!");
        msg.setFont(new Font("Arial",Font.BOLD,48));
        JOptionPane.showMessageDialog(null, msg);
        
        allow = true;
        this.dispose();
        popup.declareColor = Card.Color.Blue;
        popup.gamestage.SetPidName(popup.game.getCurrentPlayer());
        popup.gamestage.setButtonIcon();
        popup.topCardBtn.setIcon(new ImageIcon(getClass().getResource("/images/PNGs/small/" + popup.game.getTopCardImage())));
        popup.game.setCardColor(Card.Color.Blue);
        this.dispose();
    }//GEN-LAST:event_blueBtnActionPerformed

    private void yellowBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yellowBtnActionPerformed
        wildcolor = Card.Color.Yellow;
        JLabel msg = new JLabel("The Wild Card Color is Yellow!");
        msg.setFont(new Font("Arial",Font.BOLD,48));
        JOptionPane.showMessageDialog(null, msg);
        
        allow = true;
        this.dispose();
        popup.declareColor = Card.Color.Yellow;
        popup.gamestage.SetPidName(popup.game.getCurrentPlayer());
        popup.gamestage.setButtonIcon();
        popup.topCardBtn.setIcon(new ImageIcon(getClass().getResource("/images/PNGs/small/" + popup.game.getTopCardImage())));
        popup.game.setCardColor(Card.Color.Yellow);
        this.dispose();
    }//GEN-LAST:event_yellowBtnActionPerformed

    private void redBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redBtnActionPerformed
        wildcolor = Card.Color.Red;
        JLabel msg = new JLabel("The Wild Card Color is Red!");
        msg.setFont(new Font("Arial",Font.BOLD,48));
        JOptionPane.showMessageDialog(null, msg);
        
        allow = true;
        this.dispose();
        popup.declareColor = Card.Color.Red;
        popup.gamestage.SetPidName(popup.game.getCurrentPlayer());
        popup.gamestage.setButtonIcon();
        popup.topCardBtn.setIcon(new ImageIcon(getClass().getResource("/images/PNGs/small/" + popup.game.getTopCardImage())));
        popup.game.setCardColor(Card.Color.Red);
        this.dispose();
    }//GEN-LAST:event_redBtnActionPerformed

    private void greenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenBtnActionPerformed
        wildcolor = Card.Color.Green;
        JLabel msg = new JLabel("The Wild Card Color is Green!");
        msg.setFont(new Font("Arial",Font.BOLD,48));
        JOptionPane.showMessageDialog(null, msg);
        
        allow = true;
        this.dispose();
        popup.declareColor = Card.Color.Green;
        popup.gamestage.SetPidName(popup.game.getCurrentPlayer());
        popup.gamestage.setButtonIcon();
        popup.topCardBtn.setIcon(new ImageIcon(getClass().getResource("/images/PNGs/small/" + popup.game.getTopCardImage())));
        popup.game.setCardColor(Card.Color.Green);
        this.dispose();
    }//GEN-LAST:event_greenBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PickColorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PickColorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blueBtn;
    private javax.swing.JButton greenBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton redBtn;
    private javax.swing.JButton yellowBtn;
    // End of variables declaration//GEN-END:variables
}
